import { Inter } from "next/font/google";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from 'sonner';
import "./globals.css";

const inter = Inter({subsets : ["latin"]})
export const metadata = {
  title: "Welth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${inter.className}`}>
          {/* Header */}
         <Header/>
        <main className="min-h-screen">{children}</main>
        <Toaster richColors/>
        {/* Footer */}
        <footer className="bg-blue-50 py-12 ">
          <div className="container mx-auto px-4 text-center text-gray-600">
            <p>Made With ❤️ Tripti</p>
          </div>
        </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
